### ISSUE TITLE
Make sure it properly works offline

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#1]
It’s very important that taking and reading notes works flawlessly even when in a train, on a plane or when just generally offline. All changes can then be synced when online again.

**Comment by stefan-niedermann** [comment]
Current behaviour:
Reading and editing works offline without any problems. Even creating works. But there's the problem: The title is generated by the server (if you create a note offline, the title is empty until the next synchronization).
So - here are some ideas for this problem:
* Duplicate Server-Side Code to create title (don't like it much - i will have to adjust every time when server code changes)
* Use generic Title like "Local Note 1" until it has synced the next time with server.

Suggestions?

**Comment by jancborchardt** [comment]
What do you think @Henni @Raydiation @LukasReschke?

**Comment by Henni** [comment]
I think duplication is the way to go. At least this is how we solve it in the notes app.
This is important because even if you are online, the server takes about 2 seconds to respond (even on localhost).

**Comment by stefan-niedermann** [comment]
https://github.com/owncloud/notes/blob/master/service/notesservice.php#L180-L210
```php
    /**
     * get path of file and the title.txt and check if they are the same
     * file. If not the title needs to be renamed
     * @param Folder $folder a folder to the notes directory
     * @param string $title the filename which should be used, .txt is appended
     * @param int $id the id of the note for which the title should be generated
     * used to see if the file itself has the title and not a different file for
     * checking for filename collisions
     * @return string the resolved filename to prevent overwriting different
     * files with the same title
     */
    private function generateFileName (Folder $folder, $title, $id) {
        $path = $title . '.txt';
        // if file does not exist, that name has not been taken. Similar we don't
        // need to handle file collisions if it is the filename did not change
        if (!$folder->nodeExists($path) || $folder->get($path)->getId() === $id) {
            return $path;
        } else {
            // increments name (2) to name (3)
            $match = preg_match('/\((?P<id>\d+)\)$/', $title, $matches);
            if($match) {
                $newId = ((int) $matches['id']) + 1;
                $newTitle = preg_replace('/(.*)\s\((\d+)\)$/',
                    '$1 (' . $newId . ')', $title);
            } else {
                $newTitle = $title . ' (2)';
            }
            return $this->generateFileName($folder, $newTitle, $id);
        }
    }
```

**Comment by stefan-niedermann** [comment]
Closing in favor of #23 (more clear title)

**Comment by jancborchardt** [comment]
Does note deletion work without any issues?

**Comment by stefan-niedermann** [comment]
Yyyep. at least for me or did you notice any problems?

**Comment by jancborchardt** [comment]
Not yet. Cool! :) As soon as the widget ist linled to the note on click (opening in the app is fine for first pass) I will uninstall Jot and use this full-time.
