### ISSUE TITLE
How do the list item dividers work?

### ISSUE THREAD

**Issue by fxedel** [stefan-niedermann/OwnCloud-Notes#100]
I'm currently developing an Android app that uses a RecyclerView to show list items as well. I also wanted these grey divider lines between each list item (here: between each note). The only working solution for me was to add a new class extending RecyclerView.ItemDecoration and then in my fragment class use `recyclerView.addItemDecoration(...)`.

But as I can see in your source code, you didn't implemented it like this. The repository search doesn't find anything about "divider" or "ItemDecoration". So, finally my question: How exactly did you implemented these divider lines? Would be very pleased to use that in my project as well :)

**Comment by stefan-niedermann** [comment]
Well, i don't think it is the best way i have it done, but if you want to have a look at https://github.com/stefan-niedermann/OwnCloud-Notes/blob/master/app/src/main/res/layout/fragment_notes_list_note_item.xml#L43-L48 you will see i just added a 1px image at the bottom of every entry.
Hope this is helpful for you.
Regards

**Comment by fxedel** [comment]
Ok, thanks! I'll try to use it in my application as well :)
