### ISSUE TITLE
Option to synchronise notes when opening the app

### ISSUE THREAD

**Issue by af7567** [stefan-niedermann/OwnCloud-Notes#101]
When opening the ownCloud Notes app it doesn't automatically synchronise with the server but just uses the local cached copies of the notes.  I have to swipe down to get it to synchronise before opening up a note to make sure no data is lost.

A couple of times now I have gone into the app and loaded up a note, clicked edit, then realised something was missing from it.  So, I press the back button to close the note - but that automatically saves it and synchronises it and overwrites the server version with an old version (even if I didn't change anything before pressing back).

To stop this happening it would be nice to have the option for the app to auto synchronise every time it is started up, or even when it regains focus if it had been in the background.

**Comment by stefan-niedermann** [comment]
I aggree. But instead of an option, it should simply *reload* on app open. I think this issue is caused by using `onCreate`. Maybe i can use here `onResume`?

**Comment by stefan-niedermann** [comment]
> Maybe i can use here onResume?

Yeap, seems to work good. Please retest @af7567 - v0.8.0 should be on F-Droid in a few days. (Google Play a few days later)

**Comment by af7567** [comment]
Yep, it looks like it is working now thanks.
At first I thought it wasn't because it doesn't show the spinner, but the notes are all updating when opening the app, waking the phone with the app already running, and when switching back to the app from another app :)

**Comment by stefan-niedermann** [comment]
Yeap.

The spinner shows only on manual refresh (swipe to refresh), otherwise it would always show up on entering the list view - which is not needed imho and clutters the interface. the synchronization should "just happen" for users.
