### ISSUE TITLE
Scroll: bar and automatic go to the top

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/OwnCloud-Notes#105]
1. A scroll bar would be appreciated
2. The automatic going to the top is quite annoying, is it possible to disable it? 

Thanks a lot!

**Comment by stefan-niedermann** [comment]
> The automatic going to the top is quite annoying, is it possible to disable it?

This is a bug in 0.8.0 that is caused by recreating the list after synchronisation has finished. It will be fixed in 0.8.1 which should be released within the next few days.

**Comment by moshpirit** [comment]
Cool, thank you!

**Comment by stefan-niedermann** [comment]
going to the top is fixed in 0.8.1 (on F-Droid in a few days), scrollbar will be added in 0.9.0 (will take some time).

**Comment by moshpirit** [comment]
Cool, thanks!!
