### ISSUE TITLE
Synchronisation

### ISSUE THREAD

**Issue by fapsi** [stefan-niedermann/OwnCloud-Notes#107]
Hey,
first of all, thank you very much for contributing and developing this app, I really appreciate.
Unfortunately for me the synchronisation with the owncloud doesn't work.The app doesn't complain about my login credentials or something other, but in both ways (server-> androidclient, androidclient->server) there is no exchange. Is there any possibility for further debugging or are there some log files around? I would like to investigate this.
I installed the app(v0.8.1) via FDroid(v0.100-alpha1), my owcloud-instance has v. 8.2.2 and ownNote has v.1.07
Cheers!

**Comment by stefan-niedermann** [comment]
Hey,
this app is about syncing with ownCloud Note (https://github.com/owncloud/notes) - not ownNote - similar names, but this makes the difference ;-)

Regards

**Comment by fapsi** [comment]
Oh sorry, my fault. Thanks again!

**Comment by stefan-niedermann** [comment]
Thanks to corelstar (#123) there is now a better error hint if the ownCloud Notes-App is not installed on server.
