### ISSUE TITLE
Change App-Icon to ownCloud Notes Logo

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#11]
The App-Icon should be identical to the ownCloud Notes Logo.
@jancborchardt - would you like to take this one?

**Comment by jancborchardt** [comment]
Yeah, can do. Also need to fix that for the Notes web app favicon anyway. cc @Henni @Raydiation @owncloud/designers

**Comment by stefan-niedermann** [comment]
@jancborchardt If you could answer my questions on https://github.com/owncloud/android/commit/2afd2d6fb6171e94fd40a712cab9ee036b4c8058 i would be able to generate the icon myself :)

**Comment by stefan-niedermann** [comment]
Fixed by https://github.com/stefan-niedermann/OwnCloud-Notes/commit/7460d38403aa631560f70ee8f85ecfd4bd44ea2b.
