### ISSUE TITLE
App crashes when editing and delete the note or its modifications

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/OwnCloud-Notes#111]

**Comment by stefan-niedermann** [comment]
Hi @moshpirit,
can you please give me more information: Where did you get the app from? F-Droid, Google Play Store or self-built?
Which version are you using?
Can you provide exact steps to reproduce this behaviour? (Add note on android, edit it on desktop, go back to list-view in android, etc...)

**Comment by moshpirit** [comment]
Sorry, yes, of course I can:

Android 5.1.1
Version 0.81 (from F-Droid)

I think it's a problem made when I go out when it's saving the note, but I need more testing. I'll report more details!

**Comment by stefan-niedermann** [comment]
Closing in favor of #117
