### ISSUE TITLE
 incorrect connection details

### ISSUE THREAD

**Issue by frederiiiic** [stefan-niedermann/OwnCloud-Notes#113]
Hi there,

I've just installed the app on android, and it don't want to log me in. Error "Détails de connexion incorrects" in french, so something like incorrect connection details in english. I'm definitly sure of my login and password, this work on website and other app. I've tried the form with and without https, both don't work.

Did the app accept capitalize letter in pw? and in server URL?

OwnCloud Notes 0.8.1
Android 5.1
model Fairephone 2

Thanks a lot.

**Comment by frederiiiic** [comment]
Ok, i solved it.

Apparently the app don't like that there was already a "Notes" directory in my owncloud, full of *.txt in.
I just move them all to another directory, and everything is working fine now.

A bit sad of not rescaping the old notes... i'll try to find a way.

Thanks.

**Comment by stefan-niedermann** [comment]
Hm, curious. Well, this is only an android client which uses the REST-API of the server-side Notes App. This android client does not read/write files, so i am sorry to say, that i will not be able to fix this.

You may want to open an issue in the server-side part: https://github.com/owncloud/notes/issues

ciao
