### ISSUE TITLE
Automatically refresh notes at startup

### ISSUE THREAD

**Issue by giovi321** [stefan-niedermann/OwnCloud-Notes#114]
It would be very useful to have an option to automatically refresh the notes at the startup of the app. With any scheduler (like llama for example), one can automatically update the notes without opening the app.

**Comment by stefan-niedermann** [comment]
Hi @giovi321,

> automatically refresh the notes at the startup of the app

this should already happen - every time one gets to the list view, the notes should be synced. I assume you are using v0.9.0 from F-Droid? Is this correct? Please consider to use v0.7.2 while i am trying to figure out what the problem is exactly.

**Comment by stefan-niedermann** [comment]
Checked again, definitely will work with 0.9.0 (coming release).
