### ISSUE TITLE
Issue with a '*' sign

### ISSUE THREAD

**Issue by Loki3000** [stefan-niedermann/OwnCloud-Notes#115]
**Android version:** 4.4.2

**Device**: lenovo s820

**System language**: Russian

**App version:**  v0.8.1

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. click on "add note"
  3. type:
```
123*456
123*456
123*456
```
  4. save note
  5. open created note.

**Expected result:**
```
123*456
123*456
123*456
```

**Actual result**
```
123456
123456
123*456
```

**Comment by stefan-niedermann** [comment]
Hmm, well, the MarkDown-Parser thinks `*this* text should be cursive` because it is surrounded by two asterisks. Can you please check how the Browser handles this?

**Comment by Loki3000** [comment]
-- Отправлено через K-@ Mail. Извините за краткость, пожалуйста.

**Comment by Loki3000** [comment]
Seems that cursive works wrong.
![screenshot_2016-05-31-08-48-51](https://cloud.githubusercontent.com/assets/12333165/15664578/2328d898-2716-11e6-8cb8-4f5625031b43.jpeg)

**Comment by stefan-niedermann** [comment]
Agree, but unfortunately i can not fix this because the bug is caused by a 3rd-party-lib ("bypass"). I may switch to another library in the future, if i find a good one. but until then: Thanks for reporting, but can't fix.

**Comment by Loki3000** [comment]
Seems that bypass project is abandoned. So it's have to make fork and fix errors or take another lib.

**Comment by stefan-niedermann** [comment]
yep, but i don't have enough time to manage owncloud notes - forking this lib would be just too much. i agree using another lib. as soon as i find a fast, powerful library that is actuvely developed.

**Comment by stefan-niedermann** [comment]
yep, but i don't have enough time to manage owncloud notes - forking this lib would be just too much. i agree using another lib. as soon as i find a fast, powerful library that is actuvely developed.
