### ISSUE TITLE
Every touch brings to the top

### ISSUE THREAD

**Issue by sprnza** [stefan-niedermann/OwnCloud-Notes#118]
Hi there!
thank you for the great app!
I've faced with a very annoying bug. Every tap on a note preview brings me to the top of it. The only chance to have it scrolled to the bottom is to do it continiously swapping down and catching while it moves.
I use 0.8.1 from f-droid

**Comment by stefan-niedermann** [comment]
Hm, i'm sorry i can not reproduce it. Can you reproduce with the current master branch? Otherwise you could wait for 0.9.0 which has many overall code improvements

**Comment by moshpirit** [comment]
Came here because this is happening to me on last version on F-droid: 0.9.0.

Also, this bug deselect all notes selected. So if you select like your last 15 notes, it brings you to the top (I think it's an automatic sync) and deselect (even when the top bar shows "15 selected")

Android 6.0.1

**Comment by stefan-niedermann** [comment]
Tribute to @korelstar, should be fixed in v0.10.0 (will probably released after the next server-side-app release + some time for testing and bugfixing).
