### ISSUE TITLE
Time Headers in List-View (Today, Yesterday, ...)

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#12]
Maybe headers in the list between the notes make sense like:
* Today
* Yesterday
* This week
* This month
* Earlier

Originally reported from @jancborchardt.

**Comment by jancborchardt** [comment]
Huh, where did my original issue go? :D

**Comment by stefan-niedermann** [comment]
take this one ;) #6 i split it up because they were in fact two different tickets.

**Comment by jancborchardt** [comment]
Right, thanks! :)
