### ISSUE TITLE
Shorter name for activity label

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/OwnCloud-Notes#124]
Currently, name of the app (`label` of `application` in the `AndroidManifest.xml`) and the name of the main activity (`label` of `NotesListViewActivity` in the `AndroidManifest.xml`) are both set to "ownCloud Notes". Unfortunately, this name is very long and on all devices I've tested with, it is shortened in the Android launcher (i.e. on the home screen and on the alphabetical application list) to "ownCloud...", "ownCloud N..." or "ownCloud No...". This isn't very convenient, since the purpose of the app is truncated.

Therefore, I propose to change the label of the main activity in the manifest (not the name of the app!) to "Notes" resp. the localized name (e.g. in German "Notizen"). This is the way, the popular app [OpenTasks](https://github.com/dmfs/opentasks) (beside others) makes use of. I like this approach, since it focuses on the use case of the app and not on the technical realization.

**Comment by korelstar** [comment]
So, what do you think on this, @stefan-niedermann ? Any doubts? Should I make a pull request?

Since this kind of affects the design: maybe @jancborchardt could give an assessment.

**Comment by jancborchardt** [comment]
Good call, especially since this app also works with [Nextcloud](https://nextcloud.com). :)

**Comment by stefan-niedermann** [comment]
I'm not really sure. I agree, it works for Nextcloud **and** ownCloud and a shorter label would be nice. But i think about a simple DAU-user which downloads this app from Play Store or F-Droid and thinks angry "Hey, what the f***? I downloaded this app and it is not what i expected - it wants a URL and credentials from me!"
