### ISSUE TITLE
Publish App on F-Droid

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#13]
Would be great if someone could help me with F-Droid Publish. I already tried it, my results are here: https://f-droid.org/forums/topic/owncloud-notes/
Thanks for Contribution.

**Comment by jancborchardt** [comment]
You just have to add it as a text file here: https://gitlab.com/fdroid/fdroiddata/tree/master/metadata

Not sure how the pull request process works with Gitlab there though.

**Comment by stefan-niedermann** [comment]
Well, i tried it. but you have to clone fdroiddata (which you have to fork at first to your own gitlab account) and fdroidserver and you have to build the app locally with their developer tools (which didn't work for me, ruby threw errors an laughed at me...).

so really: i have very little time. if i had more, i would try to figure out how F-Droid works, but for now i will focus on the development. If you have more experience in handling F-Droid: Please. Do it :smiley:

**Comment by jancborchardt** [comment]
> and you have to build the app locally with their developer tools

Ah, really? I didn’t need to do that back a year ago or so when I added my last app there. Maybe @ciarang of F-Droid can shed light on the situation – is it the correct approach?

**Comment by stefan-niedermann** [comment]
Status Update: I replaced the Anddown Dependency with Bypass (#16) which could help to provide the App more easily on f-droid. let's see.... :)

**Comment by stefan-niedermann** [comment]
Hm @jancborchardt don't you know anyone from the ownCloud app maybe who could help here? I would provide the text file as good as i can do it. Who registered the ownCloud Beta app recently?

**Comment by AndyScherzinger** [comment]
I think @tobiasKaminski took care of that for the beta.

**Comment by stefan-niedermann** [comment]
**Update:** I've created a [Merge Request](https://gitlab.com/fdroid/fdroiddata/merge_requests/1170) - so we may get it to f-droid finally soon :)

**Comment by stefan-niedermann** [comment]
v0.4.0 is [availabe on F-Droid](https://f-droid.org/repository/browse/?fdfilter=owncloud&fdid=it.niedermann.owncloud.notes).

**Comment by jancborchardt** [comment]
@stefan-niedermann nice! :)

**Comment by AndyScherzinger** [comment]
:+1: Nice! Any particular reason for "just" supporting Lollipop and up? Just curious :)

**Comment by stefan-niedermann** [comment]
Err - Nope. I will have a look when i have time.
Well, and i tested only on 5.1 yet :wink:

**Comment by AndyScherzinger** [comment]
Yeah, no hurry I just read the version line on f-droid and thought I ask. :grin:

**Comment by AndyScherzinger** [comment]
Further infos: Support ~v19 shouldn't be a big problem since you already use the support libs :+1: 
One thing I would encourage in case you allow text selection at any place in the app you should then update the support libs to the latest version since there is a selection render bug on pre lollipop which is fixed in the actual support lib version.

**Comment by stefan-niedermann** [comment]
Some more News: Available on [Google Play Store](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes) now.

> Further infos: Support ~v19 shouldn't be a big problem since you already use the support libs :+1:
One thing I would encourage in case you allow text selection at any place in the app you should then update the support libs to the latest version since there is a selection render bug on pre lollipop which is fixed in the actual support lib version.

Thanks! Will have a look :)

**Comment by stefan-niedermann** [comment]
I was able to lower API level to 10 (Android 2.3.3) without any bigger issues. (v.0.5.1)
