### ISSUE TITLE
Bugfixes for 0.9.0

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#130]
- ~~[x] Select more then one file in the listview and bulk delete them crashes the app (but deletes successfully)~~ Not reproducable
- [x] On first initial setup a network error is shown (since there is no server configured in this state, a sync error is odd)
- [x] Server-URL-checkmark in settings activity is misaligned -> caused by using support library 24.2.0, [bug is fixed in 24.2.1](https://code.google.com/p/android/issues/detail?id=220728&can=1&q=label%3ATarget-Support-24.2.1&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened)
- [x] Test: Login has to fail if server side notes app is not installed (#131)

@korelstar your help is very welcome if you have some time :)

**Comment by korelstar** [comment]
> Select more then one file in the listview and bulk delete them crashes the app (but deletes successfully)

Do you mean "note" with "file" and this applies to the `NotesListViewActivity`? Then I can't reproduce this.

**Comment by stefan-niedermann** [comment]
@korelstar not reproducable, maybe an odd state from my local machine.
I'm still receiving the sync-error at the very first opening:
![screenshot_20160917-093035](https://cloud.githubusercontent.com/assets/4741199/18606767/85915bce-7cb9-11e6-8f14-d2ed42600978.png)

**Comment by korelstar** [comment]
Hmm. I can't reproduce the sync-error on first run with the current state in `master`. Can you debug this please? I will make a pull request with a more precise message and logging in a few minutes.
