### ISSUE TITLE
Support Subfolders

### ISSUE THREAD

**Issue by dasmaetthes** [stefan-niedermann/OwnCloud-Notes#132]
Notes in sub-folders aren't synchronized. At least they should be synchronized and shown with other notes together.

Additionally a complete sub-folder support would be nice.

**Comment by stefan-niedermann** [comment]
Depends on https://github.com/owncloud/notes/issues/2
I will implement folders when there is an API on the server app.

**Comment by dasmaetthes** [comment]
The server app shows at least the note inside sub-folders when also not sub-folders it self
QOwnNotes fully support sub-folders. 
I think it's just your attitude again not to implement something which is for other useful but you don't need it yourself

**Comment by stefan-niedermann** [comment]
**I display every note that is sent from the server through the official Notes API.** If the API does not support it and does not send it, i will not fix it with any workaround.  What do you expect? Implement webdav and fetch the complete folder structure? ;-)

> I think it's just your attitude again not to implement something which is for other useful but you don't need it yourself

Well this is basically right. I implement only things, that the official API provides. Also, i have to decide every feature i implement - is it necessairy? how many people will use it? does it clutter the UI? In this special point: Yep i think, this is absolutely useful and i'd like to have it, but i will not work around the API.

You are welcome to fork the code (even if i don't hope thats necessairy) and you are welcome to help me implement and provide a pull request as soon as the API can handle folders or categories.

**Comment by korelstar** [comment]
@dasmaetthes
> The server app shows at least the note inside sub-folders when also not sub-folders it self

Is this really true? On my installation, the current version of the server app (Notes 2.0.2) does NOT show notes inside of sub-folders.

However, the server app definitely does NOT give access to notes in sub-folders through the API. Hence, please please free to participate on owncloud/notes#2 if you want to speed this up, @dasmaetthes.

**Comment by dasmaetthes** [comment]
> Is this really true? On my installation, the current version of the server app (Notes 2.0.2) does NOT show notes inside of sub-folders.
I have to correct myself it doesn't work, I tried it few days ago,  I just moved a note into a sub-folder and it seemed working,maybe the note was still on cache that's why I could still see it.

I will have a look into it.

**Comment by dasmaetthes** [comment]
FYI
[nextcloud/notes#6](https://github.com/nextcloud/notes/pull/6)
