### ISSUE TITLE
Invalid filename when saving note

### ISSUE THREAD

**Issue by avalx** [stefan-niedermann/OwnCloud-Notes#140]
I found out a problem with saving a note after it was changed on my phone. The log file on my ownCloud server shows that the filename is invalid:

`Error  index   OCP\Files\InvalidPathException: File name contains at least one invalid character
/var/www/html/owncloud/lib/private/Files/View.php - line 757: OC\Files\View->verifyPath('/avalx/files/No...', 'Test\r.txt')
/var/www/html/owncloud/lib/private/Files/Node/File.php - line 149: OC\Files\View->rename('/avalx/files/No...', '/avalx/files/No...')
/var/www/html/owncloud/apps/notes/service/notesservice.php - line 129: OC\Files\Node\File->move('/avalx/files/No...')
/var/www/html/owncloud/apps/notes/controller/notesapicontroller.php - line 132: OCA\Notes\Service\NotesService->update(1493, 'Test\r\n=========...', 'avalx')
/var/www/html/owncloud/apps/notes/controller/errors.php - line 31: OCA\Notes\Controller\NotesApiController->OCA\Notes\Controller\{closure}()
/var/www/html/owncloud/apps/notes/controller/notesapicontroller.php - line 133: OCA\Notes\Controller\NotesApiController->respond(Object(Closure))
[internal function] OCA\Notes\Controller\NotesApiController->update(1493, 'Test\r\n=========...')
/var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 159: call_user_func_array(Array, Array)
/var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 89: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Notes\Controller\NotesApiController), 'update')
/var/www/html/owncloud/lib/private/AppFramework/App.php - line 110: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Notes\Controller\NotesApiController), 'update')
/var/www/html/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 46: OC\AppFramework\App main('NotesApiControl...', 'update', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/owncloud/lib/private/Route/Router.php - line 280: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/owncloud/lib/base.php - line 891: OC\Route\Router->match('/apps/notes/api...')
/var/www/html/owncloud/index.php - line 39: OC handleRequest()
{main}`

This only happens if the note in question was created (or modified) on my Windows computer via the QOwnNotes app. If I interpreted the log correctly it looks like the problem is because of the way Windows puts CR-LF (\r\n) in the file and on the Android it is only LF (\n)? Or is there some other problem with this issue?

**Comment by stefan-niedermann** [comment]
puuuh.... yeah, could be an issue with \r\n, .. what platform is your owncloud running? linux i assume?
Maybe a new issue in the server-side-app should be opened. of course i could hard replace \n with \r\n, but other client may have this issue too... could you open one and link please?

**Comment by avalx** [comment]
OK, I will put a request on the ownCloud/Notes site.

**Comment by stefan-niedermann** [comment]
@avalx can you reference the correspondenting issue in owncloud/notes here please? so i can stay up to date for news wheter or not this is an issue in client.

**Comment by avalx** [comment]
Here is the link for the issue: https://github.com/owncloud/notes/issues/246#issuecomment-253971684

**Comment by stefan-niedermann** [comment]
@avalx i assume this [is fixed](https://github.com/pbek/QOwnNotes/issues/408#issuecomment-265678666)?

**Comment by avalx** [comment]
No, this is still a problem. The only thing that was fixed was that particular issue for QOwnNotes (#408). I'm sorry for confusion :(.

**Comment by korelstar** [comment]
I think this is a server-app issue and I provided a patch: nextcloud/notes#31
Please test it and give feedback if this issue still exists.

**Comment by avalx** [comment]
Sorry, I'm not sure how to test this. Could you please provide some instructions?

**Comment by korelstar** [comment]
Just change one line in file `apps/notes/service/notesservice.php` of your ownCloud/Nextcloud installation:
from `$splitContent = explode("\n", $content);`
to `$splitContent = preg_split("/\R/", $content, 2);`
In the current release 2.1.0 of the notes app this is line 126, in the older version 2.0.2, this is line 106.

Then try to synchronize a note with windows line-breaks.

**Comment by avalx** [comment]
OK, I did this and it looks like it's working as expected now. Thansk for the fix.
But I still get an error in the log file on the server:
`Error	notes	OCA\Notes\Db\Note Object ( [modified] => 1481731704 [title] => TTTT [content] => TTTT
 ===========
 
 
 123
 124
 
 
 - a
 - b - c Abcfkkgk fkkffk fkfkkkf kfkgkkf Fkkfjfjg [id] => 1953 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer [modified] => integer ) )`

Is this something to worry about?

**Comment by korelstar** [comment]
Hmmm. Is this really the full log entry? This looks just like the dump of the notes object without any error message (besides the word "Error").

**Comment by avalx** [comment]
Well, that was from the Log reader app, so here is the same thing from the downloaded log file (on the Admin page - also noted as Error??!!):

`{"reqId":"WFFueH4RyqO7hxkcQlO7awAAAAE","remoteAddr":"10.55.66.116","app":"notes","message":"OCA\\Notes\\Db\\Note Object\n(\n    [modified] => 1481731704\n    [title] => TTTT\n    [content] => TTTT\r\n===========\r\n\r\n\r\n123\r\n124\r\n\r\n\r\n- a\r\n- b\n- c\n\n\nAbcfkkgk fkkffk fkfkkkf kfkgkkf\nFkkfjfjg\n    [id] => 1953\n    [_updatedFields:OCP\\AppFramework\\Db\\Entity:private] => Array\n        (\n        )\n\n    [_fieldTypes:OCP\\AppFramework\\Db\\Entity:private] => Array\n        (\n            [id] => integer\n            [modified] => integer\n        )\n\n)\n","level":3,"time":"2016-12-14T16:08:24+00:00","method":"PUT","url":"\/owncloud\/index.php\/apps\/notes\/api\/v0.2\/notes\/1953","user":"avalx"}
`

**Comment by korelstar** [comment]
That's strange. I can't find anything in the code which [could cause](https://docs.nextcloud.com/server/10/developer_manual/app/logging.html) this log entry. If not done yet, please update to the latest release of the notes app (2.1.0) and create a new issue in [nextcloud/notes](https://github.com/nextcloud/notes) if there are still problems.

Since the original issue was fixed, I'm closing this issue.

**Comment by avalx** [comment]
As suggested I manually updated to 2.1.0 and there are no more logs like this.

**Comment by stefan-niedermann** [comment]
Happy to hear that :)
