### ISSUE TITLE
Unable to sync note if title changed

### ISSUE THREAD

**Issue by am4c130d** [stefan-niedermann/OwnCloud-Notes#152]
I use a combination of OwnCloud-Notes on android and QOwnNotes on Linux and Windows with the OwnCloud Notes server.  In general, everything works really well.

I noted an issue where I'd created a document on QOwnNotes and then added the content using OwnCloud-Notes on Android.  The content would not sync, but all client instances saw the note title.  In trying to reproduce this, it appears that once a note on OwnCloud-Notes has been created, if the first line is changed, the note no longer syncs.   All other changes sync really well.

**Comment by stefan-niedermann** [comment]
I will need some time to reproduce this bug since i don't use QOwnNotes. But since i only use the Server API i barely think this is an issue caused by the android client. Could you reproduce this bug with other sync clients, too or only with the android client?

**Comment by am4c130d** [comment]
I tried to reproduce it with the built in Notes client in OwnCloud itself, as this is the only other client I have access to.  (Un)Fortunately, I am now unable to recreate the problem.  QOwnNote has been upgraded since I opened issue, and its possible that that was where the problem lay.

Again, sorry for erroneously filing an issue.

**Comment by stefan-niedermann** [comment]
Absolutely no problem :-)
