### ISSUE TITLE
Open Note on Click on Single Note Widget

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#17]
Clicking the Single Note Widget should open an Activity displaying the configured Note.

**Comment by jancborchardt** [comment]
Even better, it should open an inline display of the note, automatically open a keyboard and focus the note so you can directly type away. Like in the [Jot notes widget](https://play.google.com/store/apps/details?id=com.simplidget.jot).

**Comment by stefan-niedermann** [comment]
Since i have problems with the very limited Widget API i would prefer to do small steps to learn more about the Widget API. second step could be inline editing.
