### ISSUE TITLE
Local Search

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#19]
- In the ListView top right should be a search icon
- Clicking it should expand it to a searchbar.
- Typing should directly search in the background and display search results in a list

**Comment by mrbiber** [comment]
I'd really like to see this feature, therefore, I've started a bounty on Bountysource and donated 20 bucks for it: https://www.bountysource.com/issues/27613093-local-search

**Comment by stefan-niedermann** [comment]
Does anyone want to test the [debug-apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k)-version?
@HeaDBanGer84 @jancborchardt @mrbiber

**Comment by mrbiber** [comment]
Search  works quite nicely!  I find the synchronous updating of the list view very slow, though, and would prefer search on [enter]. 
Also titles/filenames are not included in the search which is probably a frequent use case.

**Comment by stefan-niedermann** [comment]
> Also titles/filenames are not included in the search which is probably a frequent use case.

I am searching the content. The title is generated by the first line of the content, so every titel should be searched, too. Can you give me an example note + search query where it does not work?

> Search works quite nicely! I find the synchronous updating of the list view very slow, though, and would prefer search on [enter].

Would you prefer a only-search-on-enter or would you like search as you type if it would be asynchron?

**Comment by stefan-niedermann** [comment]
@mrbiber please try the new [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k) - it works now asynchronously and should not cause any performance issues. it is still search-as-you-type.

**Comment by jancborchardt** [comment]
Search should definitely be as-you-type. Changing it to only by pressing on enter would make it even slower. There just needs to be proper feedback (like a spinner) and well, it needs to be made faster :)

**Comment by mrbiber** [comment]
I'll try the new apk asap. If the speed is good, then this is, of course, a good solution! 
As far as the filenames are concerned, this is perhaps an edge case - I'm trying to set up a synchronization between OC notes and a local wiki, where the page title is stored in the file name and thus does not necessarily reappear in the file content. I guess that it's not worth additional code complexity to cover that case.

**Comment by stefan-niedermann** [comment]
> I guess that it's not worth additional code complexity to cover that case.

I strongly aggree. Also there would be a negative performance impact when additional fields must be searched.

**Comment by jancborchardt** [comment]
Keep in mind that the file name being different from the first line is very much possible. In fact this happens a lot with desktop syncing.

For example, I have some files called »TODO« or similar things, and they have the first thing todo on the top rather than the title again.

**Comment by stefan-niedermann** [comment]
> Keep in mind that the file name being different from the first line is very much possible. In fact this happens a lot with desktop syncing.

Well this is IMHO a problem that should be addressed in the server app. Maybe by splitting title and content. I will open an issue there. Let's do a first small step and improve the search later when it's in stable branch.

**Comment by moshpirit** [comment]
Would be adding a searcher inside the note (for long notes) a good idea?

Eg: I have a huge Markdown note for activism with links and descriptions. 

This would be very useful but I also understand that might be not a very used feature for other people.

PS: I don't know if I should open a new issue for this.

**Comment by stefan-niedermann** [comment]
Hi @moshpirit 
yeap, please open a new issue. I don't know yet if it's a good idea (how many people would use it?).
But let's discuss :)

**Comment by jancborchardt** [comment]
I would definitely use an in-note search and think it’s very valuable. :)

And hooray already for the note title search!

**Comment by moshpirit** [comment]
Sure! :)
