### ISSUE TITLE
Problems during log in process

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#21]
I have yet to successfully log in because the process is a bit opaque. Here’s some first feedback :)

- [X] »URL« should be called »Server address« (less technical)
- [x] not sure if I need to type in http/https – it should work without any protocol prepended, and try with https by default
- [x] the OK button should be called »Connect« and have a spinner after clicked, and say »Connecting«. Also the input fields should be disabled to give better feedback that the process is running
- [x] I once got a checkmark right next to the server address field. Not sure if that meant the connection was then established?
- [x] hitting the back arrow on the top left causes a strange animation and all the fields to be deleted –> highly annoying
- [x] I found out you need to press the bottom »back« button to get the notes view! :D When the connection is successful, of course you should automatically be directed there
- [x] there was an error at the bottom (obscured by the Back/Home/Apps buttons) saying »URL Malformed«. Very strange technical message which doesn’t tell me what exactly the problem is. Can the server not be reached? Is http/https missing (again, add that automatically), what else?
- [x] then going to Settings presents me with again completely empty credential fields … instead the server address, username, and stars for the password (use existing one if not changed) should be preset so I don’t have to remember and put it in all over again – typing is the worst on mobile.
- [x] again here – pressing the back button should lead me back to the notes view

Maybe @David-Development @tobiasKaminsky @AndyScherzinger can help a bit? :)

**Comment by jancborchardt** [comment]
Update:
* I found out you need to press the bottom »back« button to get the notes view! :D When the connection is successful, of course you should automatically be directed there
* there was an error at the bottom (obscured by the Back/Home/Apps buttons) saying »URL Malformed«. Very strange technical message which doesn’t tell me what exactly the problem is. Can the server not be reached? Is http/https missing (again, add that automatically), what else?
* then going to Settings presents me with again completely empty credential fields … instead the server address, username, and stars for the password (use existing one if not changed) should be preset so I don’t have to remember and put it in all over again – typing is the worst on mobile.
* again here – pressing the back button should lead me back to the notes view

**Comment by jancborchardt** [comment]
And yeah, the last thing you already mentioned and which should definitely be fixed is autoloading the notes list on first connection instead of requiring a manual pull to refresh.

@stefan-niedermann hope the feedback helps! :)

**Comment by stefan-niedermann** [comment]
>  I once got a checkmark right next to the server address field. Not sure if that meant the connection was then established?

The checkmark right next to the server address field indicates if the server is reachable. it is not possible to detect if there is a running owncloud instance (because every instance responds different depending on the installed theme). so if you type: "google.de" the checkmark will appear. if you type "google." - the checkmark will disappear.

**Comment by jancborchardt** [comment]
Isn’t there a version.php or status.php we can check for that correctly? @DeepDiver1975 @davivel?

**Comment by jancborchardt** [comment]
Awesome on the fixes! :)

**Comment by stefan-niedermann** [comment]
> Isn’t there a version.php or status.php we can check for that correctly?

Thank you for the hint. App checks now for status.php https://github.com/stefan-niedermann/OwnCloud-Notes/commit/8c23698546f48d3839cccce187e8b8a515c80a3c

**Comment by stefan-niedermann** [comment]
i think all issues here are solved in master. would it be okay for you to close this issue and open a new one ("autoloading the notes list on first connection") ?
the title and discussion here might be confusing since this is the last real open task.

**Comment by jancborchardt** [comment]
Great, will do! :)

**Comment by stefan-niedermann** [comment]
closing this issue since all subtasks are done and autoload on first connection is handeled in #32.
