### ISSUE TITLE
Sort by recently modified

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#22]
The current sorting is a bit strange. Initially it seems to be alphabetically, but then it’s not lower down.
Should simply be sorted by most recently modified up top, just like in the Notes web app. :)

**Comment by stefan-niedermann** [comment]
Should be fixed in https://github.com/stefan-niedermann/OwnCloud-Notes/commit/5ba881c783d8e5f86d90832c1c4d137e23ee6e2b

**Comment by jancborchardt** [comment]
Yeeeha!
