### ISSUE TITLE
Date sometimes wrong

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#25]
On some notes from the server, the time shown in the detail view is `01.01.1970 12:00`. This should of course show the correct time.
Even better: Show the relative date, like »yesterday«, »2 days ago« etc.

**Comment by stefan-niedermann** [comment]
Fixed in https://github.com/stefan-niedermann/OwnCloud-Notes/commit/3f11bdd181fc7ef914e6329ca7082cb56e49a69d and https://github.com/stefan-niedermann/OwnCloud-Notes/commit/848ccfd31679f62826765b122d715737b53627d3
