### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#26]
Currently you need to explicitly press the confirmation checkmark in the top right. Much better would be autosave how we do it in the online Notes app and the texteditor. Save on exiting a note, or 1 second after typing has stopped (right @Henni @tomneedham?)
That would eliminate the need for the confirmation checkmark completely. Additionally we should scrap the cancel X because it is quite close to the confirmation checkmark.
We can simply show the title in the middle, the back button in the top left and the menu in the top right. Like the detail view is right now – except the floating edit icon will go because this view will already handle editing, see https://github.com/stefan-niedermann/OwnCloud-Notes/issues/3 (directly edit)

**Comment by stefan-niedermann** [comment]
- [ ] remove Cancel and Save Buttons
- [ ] save when Activity is left (e. g. pressing back button)
- [ ] save every time the user stops typing for 1 second

**Comment by jancborchardt** [comment]
> save when Activity is left (e. g. pressing back button)

As well as exiting the app using the app switcher or home button. Back button is valid for both in-app back button and system back button.
