### ISSUE TITLE
Note »Copy« function really needed?

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#28]
In the note detail actions there’s a »Copy« function. @stefan-niedermann did you build that in because you need that regularly? Because next to Share and Delete it seems a rather uncommon action for a whole note. And it would be cool if we start with the bare minimum in this app and only add stuff if really needed.

**Comment by stefan-niedermann** [comment]
Well, it works fine and it does not hurt :) i don't use it often, but is already implemented so why remove it?

**Comment by jancborchardt** [comment]
Because if something is not really needed, it takes away focus from the things which are really important. ;) I’d say just comment the code and let’s see how we fare without it for now? :)

**Comment by jancborchardt** [comment]
So – it does hurt as it takes away mental capacity. :) It’s not needed.
