### ISSUE TITLE
New note gets sorted all the way down in the list

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#30]
When you create a new note from the app and go back to the list, it’s nowhere to be found. Then you scroll all the way to the bottom and se the »Updated recently« section all the way down. To make it appear up top you have to manually refresh.

Instead it should automatically be sorted up top as it has the newest date.

**Comment by Kernald** [comment]
I'll take a look at this!

**Comment by Kernald** [comment]
@stefan-niedermann would you mind if I replace the `ListView` by a `RecyclerView`?

**Comment by stefan-niedermann** [comment]
your help is welcome :) will there be problems with `RecyclerView`? E. g. i read `RecyclerView` does not have `onItemClickListener()`?

**Comment by Kernald** [comment]
Well you obviously have other ways to achieve this. A list without being
able to click on items would be pretty useless ;-) You can set listeners on
view holders, for example.

The only thing I never made (yet) with a `RecyclerView` is sections, but
there's a first time to everything!

**Comment by jancborchardt** [comment]
@Kernald woo, awesome to have you contribute!

**Comment by stefan-niedermann** [comment]
@Kernald yeah, cool :) i'm looking forward to your PR

**Comment by jancborchardt** [comment]
Yeeeha! :) Awesome on all the new year activity :+1:
