### ISSUE TITLE
Notes app crashing on open

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#34]
The notes app is now continuously crashing for me on opening and I can not do anything at the moment. This is what I did last and what I think might have caused it:

1. Create a note
2. Add widget for it
3. Change note (including first line, title line)
4. Widget doesn’t get updated, clicking on it also leads to old note. But the list is updated
5. Then the app just starts crashing on opening.

@stefan-niedermann any idea?

**Comment by jancborchardt** [comment]
@stefan-niedermann any news here? :) Maybe @AndyScherzinger @tobiasKaminsky @Stoyicker @Kernald or @LukeOwncloud of the Files Android app can help debug?

(Btw @stefan-niedermann you’re near Nürnberg, right? You’re very welcome to join our meetups in [Munich](http://www.meetup.com/owncloud-munich/) or [Nürnberg](http://www.meetup.com/owncloud-nuernberg)! :)

**Comment by stefan-niedermann** [comment]
yeah i'm near Nürnberg. i wanted to, but monday is per definition a bad timing for me :(

no news yet, sorry.... didn't work the last few days on the app. will keep you updated if there are any news of course.

**Comment by tobiasKaminsky** [comment]
I am sorry, but I am busy with owncloud ;) 
So unfortunately I cannot help here in the nearer future...

**Comment by stefan-niedermann** [comment]
Well, the widgets are still not getting updates, but i'll have a second look into this. and at least the crashes should be fixed in the meantime.

**Comment by jancborchardt** [comment]
Yup, crashes are fixed it seems. But yeah, the widget is not getting the updates, especially when the first line (and thus the filename) is changed.

**Comment by stefan-niedermann** [comment]
Closing this because the main issue (Notes app crashing on open) is fixed.
Yeah, the Widget does not work well yet, but i keep it in mind. I want to focus on issues of the core app. You don't need to open a new ticket - if i continue work on the widget, i will keep this in mind.
