### ISSUE TITLE
Headlines rendered as normal text

### ISSUE THREAD

**Issue by X4fyr** [stefan-niedermann/OwnCloud-Notes#37]
First of all, I don't know if this is a bug or a feature.
All my headlines are formatted as normal text, except for extra spacing.
This negates the benefit of multiple level of headlines, as they all look the same.

Greetings,
X4fyr

**Comment by stefan-niedermann** [comment]
Thank you for reporting. This is a bug. I would say it's a duplicate of #24 since this seems to be caused by the upstream bypass library.

**Comment by stefan-niedermann** [comment]
Should be fixed on master-branch.
