### ISSUE TITLE
Spinner as feedback on initial notes load

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#38]
Now that the notes load initially (https://github.com/stefan-niedermann/OwnCloud-Notes/issues/32), there should be feedback about that.

Just display a loading spinner centered in the content area, and below that a short »Loading notes …«

**Comment by stefan-niedermann** [comment]
What about showing the circular loading spinner which is also shown on swipe-to-refresh? This spinner is known to the user and would provide a consistent app-behaviour on "sync with server"?

**Comment by jancborchardt** [comment]
Yeah, that would also be good and might be enough. :)

**Comment by stefan-niedermann** [comment]
Just saw at current master this is already solved :smiley:
