### ISSUE TITLE
Performance on opening a note

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#39]
Opening a note takes a tad too long when tapping on it. Is there any way to make it faster?

As a first step, it would be good to at least give feedback that the app registered the tap. Currently there’s no row highlight or anything as one is used to with other apps.

**Comment by stefan-niedermann** [comment]
I think the main problem is the bypass-library which i am using. it takes much time and i am not able to cache the rendered result (reportet to upstream, too: https://github.com/Uncodin/bypass/issues/191 - no answer yet :disappointed: ).

**Comment by jancborchardt** [comment]
Looking at the activity of that library it seems pretty inactive: https://github.com/Uncodin/bypass/commits/master – and from the description (markdown) it’s not really something we need at this point. Especially since it’s the cause of two major problems, this and the line-break issue.

I’d say let’s throw it out for now if possible. We can always reevaluate later when the issues are fixed upstream and when we really need markdown. (And when we implement markdown, it should be inline, like in the Notes web app.)
