### ISSUE TITLE
Mention license, source code and call to contribution in the »About« section

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#40]
That would be cool to underline this is open source and contributions are welcome. :)

**Comment by stefan-niedermann** [comment]
yeah right. i will do this after #11 - since i will have to change the about-page then anyway.

**Comment by stefan-niedermann** [comment]
Just some thoughts about design:
Maybe some tabs?

----

# Credentials
## Maintainer
Stefan Niedermann
## Contributors
### Development
HeaDBanGer84
### Translation
pejakm
### Testing
Jan C. Borchardt

----

# Contribution

Source Code: <GithubLink>
Issue Tracker: <GithubIssuesLink>

# License

This App is licensed under the GPLv2
<Here Full License Text>

**Comment by jancborchardt** [comment]
@stefan-niedermann I would simplify the »About« page to just be one page, without tabs. Right now it seems to be the most complex part of the app. ;)

Like this maybe:

> Logo
> ##### ownCloud Notes
> 
> Developed by [Stefan Niedermann (Niedermann IT services)](), [HeaDBanGer84](https://github.com/headbanger84), [Jan-Christoph Borchardt (design)](http://jancborchardt.net), pejakm (Serbian translation)
> 
> You can join by [contributing code and design](https://github.com/stefan-niedermann/OwnCloud-Notes/) as well as [testing and opening issues](https://github.com/stefan-niedermann/OwnCloud-Notes/issues/)! :)
> The app is licensed under the [GNU GPLv2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html).
>
> Version 0.4.0
> [Here we could have a button to check for updates.]


We could also mention @HeaDBanGer84 by name. :) And is GPLv2 really the best choice of license, given it’s not the latest?

**Comment by stefan-niedermann** [comment]
> I would simplify the »About« page to just be one page, without tabs.

I'll think about it

> We could also mention @HeaDBanGer84 by name. :)

His decision ;) Not everyone wants to read his real name everywhere ;) - if @HeaDBanGer84 wants, i will of course add his real name.

>  And is GPLv2 really the best choice of license, given it’s not the latest?

Just had a look at the LICENSE-file, it's licensed under GPLv2+ (gplv2 or later). I also thought about switching to AGPL.

**Comment by jancborchardt** [comment]
AGPL doesn’t make a lot of sense since it’s not hosted software, but I would recommend GPLv3+.

**Comment by stefan-niedermann** [comment]
Thank you for feedback. I will keep it as it is for now. I plan to migrate to GPLv3+.

**Comment by jancborchardt** [comment]
@stefan-niedermann thing is that it’s a funnel: Sure not every normal user will view it. But if it looks simpler, then we get more people to contribute. If it’s this convoluted big menu thing, people are less likely to be able to navigate through it and find what they are looking for. It’s just an »About« page after all.

(Also, usually not every single translator is listed because that just ends up being too much. I would recommend to link to the Transifex app page, if that is used. That has the added bonus of leading people to the place to translate.
