### ISSUE TITLE
Align text of date dividers with the note text

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#41]
Currently the text of the »yesterday«, »this week«, »earlier« headers is too far to the left. It should be left aligned with the text of the notes to look nicer. :)

**Comment by stefan-niedermann** [comment]
Is in v0.4.0 (which i released just some minutes ago).
I also adjusted the README.md-file:

> Access: Since this app is currently not available in any Appstore, i will provide some versions in my ownCloud instance. Feel free to download and distribute. But be careful: This kind of installation does not include any kind of automatic updates, so you will have to check manually for new security and feature updates.

http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k

**Comment by jancborchardt** [comment]
Nice, good call on distributing the apks like that. :) Will check out v0.4.0 now.
