### ISSUE TITLE
On initial start, deactivate connect button initially

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#45]
At least the server address and the username field should have a value before the Connect button is enabled.

**Comment by stefan-niedermann** [comment]
Would it be enough logic if:

User starts app -> Button is disabled.
If url is not empty AND username is not empty -> Button is enabled.
If url is empty OR username is empty -> Button is enabled.

**Comment by stefan-niedermann** [comment]
@jancborchardt Can you confirm this logic is enough? You can retest if you want: http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k (app-debug.apk). So we can close this issue.

**Comment by jancborchardt** [comment]
> If url is empty OR username is empty -> Button is enabled.

I guess you meant to say _dis_abled here?

**Comment by stefan-niedermann** [comment]
Ah, of course :) edited my comment.
