### ISSUE TITLE
Username field is multiline

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#46]
Filling out the server address, you can use the »enter button« of the keyboard to continue to the next field for typing in the username. There however, using the enter button creates a new line. This makes little sense as usernames can not be multiline. ;) Instead, it should work the same and continue to the password field.

**Comment by stefan-niedermann** [comment]
Fixed in 6e74f9e.
see [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k)
