### ISSUE TITLE
Pressing enter when finished writing in the password field should automatically connect

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#47]
In the initial connection screen, pressing the enter button on the keyboard (which has a checkmark in it) should automatically trigger the connect button. Right now you need to manually click it when you are done.

**Comment by stefan-niedermann** [comment]
see [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k)
