### ISSUE TITLE
In edit view, text alignment should be the same as in note view

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#50]
Currently when switching to the edit view, the text is squished too far to the edges. It should have the same margin as when you view the note.

**Comment by stefan-niedermann** [comment]
see [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k)

**Comment by jancborchardt** [comment]
Awesome on all the fixes! :) You rock!
