### ISSUE TITLE
Changing screen orientation causes data loss

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#55]
1. Edit a note
2. Exit edit mode
3. In view mode, rotate the device to switch to landscape mode.

The new edit will be lost. cc @stefan-niedermann

**Comment by stefan-niedermann** [comment]
Technical Solution: use onSaveInstanceState to remember edited note. Because on every screen orientation change onCreate() is called which uses the original given note.
