### ISSUE TITLE
Show Excerpt instead of Modified Date in List-View

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#6]
Right now the modified/creation date is focused a lot, in the list and in the header.

In the list it would be cooler to show the next line of the note (maybe even the next 2) to see more of the note. It’s sorted by date anyway so it’s not as important.

**Comment by stefan-niedermann** [comment]
There should be an API on Server-Side to generate an excerpt (15 - 20 words?). So every client could display the same text. It should not be generated in the app itself.
https://github.com/owncloud/notes/issues/163

**Comment by stefan-niedermann** [comment]
@jancborchardt please move second part (Headers between list) to a seperate issue.
