### ISSUE TITLE
NullPointer when trying to save

### ISSUE THREAD

**Issue by ibleedbinari** [stefan-niedermann/OwnCloud-Notes#65]
I keep encountering a NullPointer after editing any note and trying to save on exit. After encountering the crash one time, the app always crashes on launch until you clear data.

```
01-30 10:15:49.745 E/AndroidRuntime(12186): FATAL EXCEPTION: main
01-30 10:15:49.745 E/AndroidRuntime(12186): Process: it.niedermann.owncloud.notes, PID: 12186
01-30 10:15:49.745 E/AndroidRuntime(12186): java.lang.NullPointerException: Attempt to invoke virtual method 'long it.niedermann.owncloud.notes.model.Note.getId()' on a null object reference
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.updateNote(NoteSQLiteOpenHelper.java:228)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$UploadEditedNotesTask.onPostExecute(NoteServerSyncHelper.java:172)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$UploadEditedNotesTask.onPostExecute(NoteServerSyncHelper.java:157)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at android.os.Looper.loop(Looper.java:148)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at android.app.ActivityThread.main(ActivityThread.java:5466)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at java.lang.reflect.Method.invoke(Native Method)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-30 10:15:49.745 E/AndroidRuntime(12186): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

**Comment by stefan-niedermann** [comment]
Can you please describe steps to reproduce?

And in the meantime: can you clear app data and test if it works when you reconnect?

**Comment by ibleedbinari** [comment]
Steps to reproduce:
1. Open any note
2. Make any change
3. Go back (app tries to save and crashes)

Problem occurs again after clearing data and setting up server again fresh.

**Comment by stefan-niedermann** [comment]
Hm... can you please add the following information: Which device are you using? which exact version do you use and from which app store? Did you have internet connection when you tried it or did you maybe switch 3g/wlan when trying this?

**Comment by ibleedbinari** [comment]
Nexus 5X running CyanogenMod 13 20160129-NIGHTLY Android 6.0.1
Affects version 0.4.0 and 0.5.0, both from F-Droid
Internet was active, WLAN at the time, no network switch either try.

**Comment by stefan-niedermann** [comment]
Hard to discover. I assume you only used your mobile phone and did not use the webinterface at the same time?
Have you tried to update your mobile phone via swipe2refresh? This should create a clean data level on your phone. (swipe from top to bottom in the list view).

**Comment by stefan-niedermann** [comment]
I could reproduce this
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long it.niedermann.owncloud.notes.model.Note.getId()' on a null object reference
at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.updateNote(NoteSQLiteOpenHelper.java:228)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$UploadEditedNotesTask.onPostExecute(NoteServerSyncHelper.java:172)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$UploadEditedNotesTask.onPostExecute(NoteServerSyncHelper.java:157)
```

which seems to be the same problem like you have.
My steps to reproduce:
1. open note on mobile phone and start editing it
2. delete note (e.g. via web interface)
3. type something on mobile phone (which causes auto-save)
4. exception.

**Comment by stefan-niedermann** [comment]
I have created a fix which will prevent the app from crashing.
Please wait 1 or 2 days until version 0.5.2 is available on F-Droid and retest.

I will create a follow-up ticket to refactor this and ask user, whether he wants to delete his local note or recreate the note on server.

Thank you.

**Comment by ibleedbinari** [comment]
I'm fine with switching the release source/signature. Do you have a 0.5.2 build available?

**Comment by stefan-niedermann** [comment]
Nice :)

You can try [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k) (mentioned in the README.md)

**Comment by ibleedbinari** [comment]
That build says it is version 0.5. Was it updated?

**Comment by stefan-niedermann** [comment]
Please retry

**Comment by ibleedbinari** [comment]
That fixed it. Thanks!
