### ISSUE TITLE
Handle remote note deleted

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#66]
This is a follow-up-ticket for #65.
# Situation:
1. User starts editing a note on his mobile phone.
2. User deletes note via web interface without leaving edit-mode on mobile
3. User causes autosave through leaving the edit-mode or further editing
4. How should this be handled?
   - **Delete local** note
   - **Recreate remote** note
   - Let **user choose**

cc: @jancborchardt

**Comment by jancborchardt** [comment]
I’d say let’s err on the side of caution here – recreating the remote note seems to be the best course of action. It’s minimally invasive and the scenario is also pretty edge-casey.

**Comment by korelstar** [comment]
With #123, the recreation is implemented (like before?). Hence, this can be closed(?)
