### ISSUE TITLE
Enhancement: integrate a singular and plural version of <string name="ab_selected">

### ISSUE THREAD

**Issue by ageru** [stefan-niedermann/OwnCloud-Notes#68]
Hi,

On the notes listing page, it is possible to long-press one note to select it, and then to select several others.

The title bar will change depending on how many notes have been selected: "1 selected", "2 selected", etc.

In French - and possibly other languages - "selected" in that context has a singular and a plural version. I hacked something to cover both singular and plural in French here, but it's not really graceful.

With that in mind, it might be useful to integrate a singular and a plural version of the string "ab_selected" in the context of translations.

Many thanks for considering this.

**Comment by stefan-niedermann** [comment]
I need some information for initial implementation:
Which cases are handled specially by android?
["zero" | "one" | "two" | "few" | "many" | "other"]
And what are the correct french wordings? (Just post them here, i will copy them initially).

**Comment by stefan-niedermann** [comment]
Is this correct?
```xml
        <item quantity="one">%d selectionnée</item>
        <item quantity="other">%d selectionnées</item>
```

**Comment by ageru** [comment]
Hi Stefan,

Apologies for the late answer.

Indeed, you implemented it right for French. Here is how it works for froggies:
- 0 selectionnée
- 1 selectionnée
- 2 selectionnées
- 3 sélectionnées
Etc.

Basically, French switches to plural from 2.

Was it Russian that has different cases for 1, few many? I remember coming accross this once, I'll need to check.

Anyway, thanks for following up so quickly :)

Kind regards.

**Comment by stefan-niedermann** [comment]
You're welcome :)
