### ISSUE TITLE
Can't copy text when not in edit mode

### ISSUE THREAD

**Issue by haarp** [stefan-niedermann/OwnCloud-Notes#70]
In most apps, you can long-press text to get a selection and to copy text into the clipboard. This only works in this app if you go to edit mode first, not in the main view.

**Comment by haarp** [comment]
Wow, you're fast. Thanks a lot!

**Comment by stefan-niedermann** [comment]
You're welcome. Was just one line :wink:
Will be i next release (0.6.0).
