### ISSUE TITLE
Provide feedback on wrong credentials

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/OwnCloud-Notes#72]
When a user trys to log in for the first time or changes his server settings, there is no visual feedback given, when the username/password is wrong.

Expected behaviour:
- user clicks "connect"
- username/password is wrong
- [toast](http://developer.android.com/guide/topics/ui/notifiers/toasts.html) appears and disappears after 3 seconds

**Comment by sedrubal** [comment]
:+1:
