### ISSUE TITLE
Minimum Android version

### ISSUE THREAD

**Issue by 9662** [stefan-niedermann/OwnCloud-Notes#75]
Currently, both the apk in your ownCloud and on F-Droid have a minimum Android version of 5.1. I have a device on 4.2.1.

Is there any chance this could be built against such a version?

**Comment by 9662** [comment]
Never mind. Now it has installed from F-Droid somehow.

Apologies for the noise.

**Comment by stefan-niedermann** [comment]
No problem, v0.5.0 required API Level 23. - This has been fixed in v0.5.1 - Now API Level 10 is required (Android 2.3.3).

**Comment by 9662** [comment]
Ok, that explains. F-Droid did a refresh in between the first and the second time I looked. Cheers. ☺
