### ISSUE TITLE
Update heading after text has changed

### ISSUE THREAD

**Issue by fxedel** [stefan-niedermann/OwnCloud-Notes#80]
The heading is always the first line. But when I change the first line, the heading only updates to the new value after closing the note and refreshing. Before that, there are two different headings:

![photo_2016-02-02_20-39-23](https://cloud.githubusercontent.com/assets/7782229/12761924/4afc4c1e-c9ed-11e5-89ea-b8bd93793220.jpg)

Fix would be nice :)
I'm using the F-Droid apk, version 0.5.2.

**Comment by stefan-niedermann** [comment]
Related to #74. Title usually gets generated on server (so the new title is only available after the note has been synchronized). But i already have a method on client to generate title, so i think it's not too complicated at all.
