### ISSUE TITLE
wrong username or password

### ISSUE THREAD

**Issue by eggithub** [stefan-niedermann/OwnCloud-Notes#82]
Hi there,

Just installed the app from f-droid. I think I have the server address and credentials filled out correctly but still the app shows "invalid username or password".

info:
able to connect to server from other apps/browser
notes app version 0.6.0 from f-droid
owncloud 8.2.2 with notes enabled
android 4.3
self signed certificate, imported in android
logcat shows no usable output, except "invalid login"

no clue what i'm doing wrong here.

What is the format of the server address? https://servername:port/owncloud ?

cheers!

**Comment by stefan-niedermann** [comment]
Hi, can you provide a demo-account for your owncloud instance and send me the credentials via email?

**Comment by eggithub** [comment]
Will do tonight. Can you provide me with an IP(range) to let you through my firewall?

**Comment by stefan-niedermann** [comment]
sadly no, i don't have a fix ip address. i can give you my current address when i can test it, but this will change after 24 hours :disappointed:

**Comment by eggithub** [comment]
you can give me multiple subnets if you want...

**Comment by eggithub** [comment]
Hi, 

I set up an account for you on my server. 

User: stefan
Pass: nieder127mann
URL: https://skyrockit.us.to:4443/owncloud

Now all I need is an IP or range so I can grant you access.

Gr. Sander

**Comment by stefan-niedermann** [comment]
My current IP-Address is 84.149.154.229

**Comment by eggithub** [comment]
you can try now...

**Comment by stefan-niedermann** [comment]
I was able to reproduce the exception.
But i do not know yet why it is caused. I exported your cert and imported it into android. Sadly i have not very much experience with self signed certificates...

![sslpeerunverifiedexception](https://cloud.githubusercontent.com/assets/4741199/12826998/f1c1b05c-cb7d-11e5-85b0-bca8e3756b09.png)

```
Hostname x.to not verified:
    certificate: sha1/cjrKVKacPs8+ynDotfYdxGlZi3E=
    DN: CN=x.x.15.3,O=\ \ ,ST=\ \ ,C=\ \ 
    subjectAltNames: []
```

**Comment by eggithub** [comment]
me neither, just know how to create one. I think I remember something about self signed certificates and owncloud client from 2 years ago about not being able to connect. something to do with the fact that the CN had to be the same as the IP adres or hostname. but I remember it that vaguely that I don't know if this was the real issue; still could be related though

**Comment by stefan-niedermann** [comment]
Maybe this [Stackoverflow-answer](http://stackoverflow.com/a/16073479) could be useful...

> Make sure that the certificate that you are installing is actually a CA certificate and not just a simple x509 certificate. Unfortunately the certificate installer that comes with ICS will gladly install the certificate even if it's not a CA certificate. It will misleadingly say that the certificate was successfully installed. It will even put the file under /data/misc/keystore. However, i

**Comment by stefan-niedermann** [comment]
Some requests reached me from people who have the same problem. I think the general issue is accepting self signed certificates.
If you are ok with the decision i would close this issue in favor of #73.

**Comment by eggithub** [comment]
Fine with me. I'll check the other post for updates. 

Cheers!

**Comment by fxedel** [comment]
I also have a self-signed certificate and I get the exact same error. The only solution for me was to change from https to http.
