### ISSUE TITLE
Feature Request: Task Lists in Notes

### ISSUE THREAD

**Issue by cacula** [stefan-niedermann/OwnCloud-Notes#86]
Would be nice if it would be possible to add Task Lists to notes
e.g. like in github

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

see https://guides.github.com/features/mastering-markdown/

**Comment by stefan-niedermann** [comment]
Yeah, would be cool.
I am using [bypass-project](https://github.com/Uncodin/bypass) to render the markdown, so this feature request should go to their repository.

**Comment by cacula** [comment]
done

https://github.com/Uncodin/bypass/issues/201

**Comment by stefan-niedermann** [comment]
PS.: I'm thinking about changing the MarkDown library since this project seems to be not maintained (last changes are month ago)... If anyone know a good one...
