### ISSUE TITLE
Heading doesn't allow hyphens

### ISSUE THREAD

**Issue by fxedel** [stefan-niedermann/OwnCloud-Notes#87]
When I use a hyphen ("-") in a notes' first line, it doesn't show up in the heading. However, the first line stays unchanged.
![_20160210_123435](https://cloud.githubusercontent.com/assets/7782229/12948692/f5423e4c-d003-11e5-81ec-940e01ba6319.JPG)

**Comment by fxedel** [comment]
Additional note: I haven't synced yet, the heading generation has to be the one by @stefan-niedermann.

**Comment by stefan-niedermann** [comment]
Yeah, basically the [server-side](https://github.com/owncloud/notes/blob/master/service/notesservice.php#L183-L215) code has to be ported from php to java (https://github.com/stefan-niedermann/OwnCloud-Notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/util/NoteUtil.java#L74-L82)

**Comment by fxedel** [comment]
![bildschirmfoto vom 2016-04-07 18-47-07](https://cloud.githubusercontent.com/assets/7782229/14359369/62005c34-fcf1-11e5-85ed-ff9661e5c582.png)

As you can see, the desktop version doesn't remove markdown code, it simply uses the first line.

I don't exactly know the code location where that title is generated. Maybe this: [js/app/controllers/notecontroller.js#L20-23](https://github.com/owncloud/notes/blob/master/js/app/controllers/notecontroller.js#L20-23)? Seems so, because the default title (if first line is empty) is "New note":

    $scope.updateTitle = function () {
        $scope.note.title = $scope.note.content.split('\n')[0] ||
            t('notes', 'New note');
    };

In my opinion, we don't need `getLineWithoutMarkDown(...)` in `generateNoteTitle(...)` at all. Something like should be enough (haven't tested yet):

    String[] lines = content.split(System.getProperty("line.separator"));
    return
        lines.length() > 0 && !lines[0].trim().equals("") ?
        lines[0] :resources.getString(R.string.new_note);
