### ISSUE TITLE
Issues when editing or creating notes without sync

### ISSUE THREAD

**Issue by fxedel** [stefan-niedermann/OwnCloud-Notes#88]
My OwnCloud installation is on a local server, so I can only sync when I'm at home and with my WiFi network connected.

When I add or edit notes on the go without syncing, wait a while and then sync back at home, there are three things that can happen. I haven't found out which of them happens when (maybe it's random):
1. The note is synced correctly, I can see the whole content on my computer.
2. The note's content isn't there anymore, neither on my computer, nor on my phone. Veeery bad if you have written much text because it's lost then.
3. The whole note disappears. Even a bit worse than 2.

**Comment by fxedel** [comment]
So I decided to make some more specific studies. Before each test, I've deleted all existing notes and synced until they got removed on phone and server.

## Study 1: Create new note, then sync

1. Turn WiFi (sync) off.
2. Open the notes app.
3. Press the + fab.
4. Enter this text (n means the index of current test)

    ````
    Note n
    
    Content
    ````

5. Press "Save".
6. Pull down to refresh.
7. Turn WiFi (sync) on (wait a while during connecting).
8. Pull down to refresh.

### Results

1. Case 1 (see first post)
2. Case 1
3. Case 1
4. Case 1
5. Case 1

:arrow_right: Seems to work :heavy_check_mark:


## Study 2: Create new note and edit it, then sync

1. Turn WiFi (sync) off.
2. Open the notes app.
3. Press the + fab.
4. Enter this text (n means the index of current test)

    ````
    Note n
    ````

5. Press "Save".
6. Pull down to refresh.
7. Tap on the note, then on the edit fab.
8. Add these lines:

    ````
    
    Content
    ````

9. Press "Back" two times (until the main screen is shown).
10. Pull down to refresh.
11. Turn WiFi (sync) on (wait a while during connecting).
12. Pull down to refresh.

### Results

1. Case 3
2. Case 3
3. Case 3
4. Case 3
5. Case 3

:arrow_right: That seems to make problems! :x: 


## Study 3: Create new note, sync it, edit it, then sync again

1. Do study 1 with this text:

    ````
    Note n
    ````
    
2. Turn WiFi (sync) off.
3. Tap on the note, then on the edit fab.
4. Add the lines:

    ````
    
    Content
    ````

5. Press "Back" two times (until the main screen is shown).
6. Pull down to refresh.
7. Turn WiFi (sync) on (wait a while during connecting).
8. Pull down to refresh.

### Results

1. Case 1
2. Case 1
3. Case 1

:arrow_right: Seems to work :heavy_check_mark:


## Study 4: Create new note, sync it, edit it multiple times, then sync again

1. Do study 1 with this text:

    ````
    Note n
    ````
    
2. Turn WiFi (sync) off.
3. Tap on the note, then on the edit fab.
4. Add the lines:

    ````
    
    Content
    ````

5. Press "Back" two times (until the main screen is shown).
6. Pull down to refresh.
3. Tap on the note, then on the edit fab.
4. Change the last line to:

    ````
    Lorem ipsum.
    ````

5. Press "Back" two times (until the main screen is shown).
6. Pull down to refresh.
7. Turn WiFi (sync) on (wait a while during connecting).
8. Pull down to refresh.

### Results

1. Case 1
2. Case 1
3. Case 1

:arrow_right: Seems to work :heavy_check_mark:


## Summary

Obviously, the app has problems with editing notes that have never been synced with the server yet. Maybe there are more complex problems (perhaps with multiple notes?) that also cause Case 2. But maybe everything works again if you'd fix study 2. Nobody knows ;-)

**Comment by stefan-niedermann** [comment]
Great description! Thank you very much, this is very useful.

**Comment by stefan-niedermann** [comment]
I think i have an idea about what causes this issue:
1. User creates note (Flag CREATED is set in db)
2. User edits note (Flag EDITED is set in db)
3. User synchronizes note (Trys to use UPDATE method for EDITED note, but on server there is this note not available)
This causes an error and the note gets damaged.

**Comment by fxedel** [comment]
That makes sense. Looking forward to a fix :)

**Comment by stefan-niedermann** [comment]
@fxedel could you please test [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k)?

**Comment by fxedel** [comment]
I'm sorry, but the in study 2 described bug still remains, the note disappears :(

**Comment by nytche** [comment]
I have just lost an offline written article after synthing, any solution?

**Comment by stefan-niedermann** [comment]
I'm still trying to find a solution. Maybe v0.7.1 (should be soon on f-droid) could fix this issue. https://github.com/stefan-niedermann/OwnCloud-Notes/commit/eb6e2b0d74e7c283d6f7921f8cee1ed4191193d7
Please be patient, i have not very much time to develop this app.

**Comment by stefan-niedermann** [comment]
@fxedel Could you please retest with v0.7.2 (Available on Play Store and F-Droid)

**Comment by fxedel** [comment]
@stefan-niedermann Just tested it, seems to be working now. Thanks! I'll let you know if I experience any problems in future, but study 2 works now as expected.
