### ISSUE TITLE
Synchronisation does not work at all

### ISSUE THREAD

**Issue by kidexx** [stefan-niedermann/OwnCloud-Notes#89]
After installing the .crt file the logon does work, but no synchronisation at all. I am able to create notes on the mobile, but neither they are transferred to OwnCloud nor I can see the notes from owncloud. I don't get an error message.
Only special thing on my owncloud installation: It is in a subfolder of the domain, no own subdomain - is this maybe related?

**Comment by fxedel** [comment]
The subfolder won't be the problem because my installation is also in a subfolder and for me, everything is working ;-)

**Comment by kidexx** [comment]
OK, then only the question remains why it does not work at all. Unfortunately I don't get an error message. The version of owncloud: ownCloud 8.2.2 (stable)

**Comment by fxedel** [comment]
Did you check logcat messages?

**Comment by kidexx** [comment]
Yes, I don't see there something which seems to be related.

**Comment by kidexx** [comment]
Ha, solved the problem. There are two Notes-Apps: The„OwnNote“ App from Ben Curtis and the „Notes“ App from Bernhard Posselt, Jan-Christoph und Borchardt.
The last note must be used.
In the other note app: https://f-droid.org/repository/browse/?fdfilter=myownnotes&fdid=org.aykit.MyOwnNotes
I got the error message with "JSON Format" which leaded me to: https://thomas-leister.de/internet/owncloud-notes-mit-android-kein-gueltiges-json-format/

**Comment by stefan-niedermann** [comment]
Sorry for late answer. Yeah, as mentioned in the preview, this is a client for [ownCloud Notes](https://github.com/owncloud/notes/), not ownNotes.

Regards

**Comment by stefan-niedermann** [comment]
Thanks to corelstar (#123) there is now a better error hint if the ownCloud Notes-App is not installed on server.
