### ISSUE TITLE
No Synchronization

### ISSUE THREAD

**Issue by kowarschick** [stefan-niedermann/OwnCloud-Notes#90]
Source: Google Play Store, v0.7.0, Sony Xperia Z2 tablet and Sony Xperia Z2 smartphone

I've installed ownCloudNotes ontwo devices.
I can connect to a ownCloud server (version 8.2) via https (certified by letsencrpyt). I can write notes. 
But those notes are not stored within the onenote app (OwnNote 1.05,  QOwnNotesAPI 0.4.2) .
And if I switch to the second device, the notes I've created on the first device are not displayed.

How can I enable synchronization?

**Comment by stefan-niedermann** [comment]
Hi,

like mentioned in the Readme.md-File and on Google Play, the required Server app is not "ownNote" but "ownCloud Notes".
You will have to install [this app](https://github.com/owncloud/notes/) on your server.

**Comment by stefan-niedermann** [comment]
Thanks to corelstar (#123) there is now a better error hint if the ownCloud Notes-App is not installed on server.
