### ISSUE TITLE
multiple lines shown on one line

### ISSUE THREAD

**Issue by af7567** [stefan-niedermann/OwnCloud-Notes#95]
With some of my notes which have strike through text I am getting all the lines shown on one long line until getting to a black line.

**Comment by af7567** [comment]
Here is a screenshot showing a note in the app and the same note from the web interface.

https://csparker.uk/owncloud/index.php/s/3BaXLmhmMe8DR8f

**Comment by fxedel** [comment]
Hi!

Unfortunately, this bug isn't new. Have a look at #24. It's a problem with the markdown library. But @stefan-niedermann already wrote a fix for this, it'll be added in version 0.8.0.

**Comment by af7567** [comment]
Ah OK. Thanks. 
I did look at older issues to see if someone had mentioned it but I obviously didn't look back far enough :)
